import React, { useState, useRef, useEffect } from 'react';
import { Send, Plane, MapPin, Calendar, DollarSign, Loader2, Download, Share2, ExternalLink } from 'lucide-react';

const TravelPlannerAgent = () => {
  const [messages, setMessages] = useState([
    {
      role: 'assistant',
      content: "Welcome to Event Horizon. I'm your AI journey architect. Fill in the essential details below or simply describe your vision—I'll craft the perfect itinerary for your travels across space and time.",
      timestamp: new Date()
    }
  ]);
  const [input, setInput] = useState('');
  const [isLoading, setIsLoading] = useState(false);
  const [searchStatus, setSearchStatus] = useState('');
  const [itinerary, setItinerary] = useState(null);
  const [isCustomizing, setIsCustomizing] = useState(false);
  const [activeTab, setActiveTab] = useState('chat'); // 'chat' or 'itinerary'
  const messagesEndRef = useRef(null);
  
  // Structured input fields
  const [showForm, setShowForm] = useState(true);
  const [tripDetails, setTripDetails] = useState({
    fromLocation: '',
    toLocation: '',
    startDate: '',
    endDate: '',
    budget: '',
    travelers: '2',
    pointsMiles: '',
    preferences: ''
  });

  const scrollToBottom = () => {
    messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' });
  };

  useEffect(() => {
    scrollToBottom();
  }, [messages, searchStatus]);

  const generateItineraryPDF = () => {
    if (!itinerary) return;
    
    const content = `
TRAVEL ITINERARY
================

Destination: ${itinerary.destination}
Dates: ${itinerary.startDate} to ${itinerary.endDate}
Total Budget: $${itinerary.totalBudget}

${itinerary.flights ? `
FLIGHTS
-------
${itinerary.flights.map(f => `${f.departure} → ${f.arrival}
Airline: ${f.airline}
Price: $${f.price}
Book: ${f.bookingLink}
`).join('\n')}
` : ''}

${itinerary.hotels ? `
ACCOMMODATIONS
--------------
${itinerary.hotels.map(h => `${h.name}
Rating: ${h.rating} ⭐
Price: $${h.price}/night
Address: ${h.address}
Book: ${h.bookingLink}
`).join('\n')}
` : ''}

${itinerary.activities ? `
DAILY ITINERARY
---------------
${itinerary.activities.map(day => `
Day ${day.day}: ${day.date}
${day.items.map(item => `  • ${item.time} - ${item.activity} ${item.location ? `(${item.location})` : ''}`).join('\n')}
`).join('\n')}
` : ''}

${itinerary.restaurants ? `
RECOMMENDED RESTAURANTS
-----------------------
${itinerary.restaurants.map(r => `${r.name} - ${r.cuisine}
${r.priceRange} | ${r.rating} ⭐
${r.address}
`).join('\n')}
` : ''}

Budget Breakdown:
-----------------
Flights: $${itinerary.budgetBreakdown?.flights || 0}
Hotels: $${itinerary.budgetBreakdown?.hotels || 0}
Activities: $${itinerary.budgetBreakdown?.activities || 0}
Food: $${itinerary.budgetBreakdown?.food || 0}
Miscellaneous: $${itinerary.budgetBreakdown?.misc || 0}
---
TOTAL: $${itinerary.budgetBreakdown?.total || itinerary.totalBudget}

Generated by AI Travel Agent
    `;

    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `itinerary-${itinerary.destination.replace(/\s+/g, '-').toLowerCase()}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const shareItinerary = () => {
    if (!itinerary) return;
    
    const shareText = `Check out my ${itinerary.destination} trip itinerary!\n\nDates: ${itinerary.startDate} - ${itinerary.endDate}\nBudget: $${itinerary.totalBudget}\n\nGenerated by AI Travel Agent`;
    
    if (navigator.share) {
      navigator.share({
        title: `${itinerary.destination} Trip Itinerary`,
        text: shareText
      });
    } else {
      navigator.clipboard.writeText(shareText);
      alert('Itinerary summary copied to clipboard!');
    }
  };

  const handleFormSubmit = () => {
    // Validate required fields
    if (!tripDetails.toLocation || !tripDetails.startDate || !tripDetails.endDate || !tripDetails.budget) {
      alert('Please fill in destination, dates, and budget!');
      return;
    }

    // Convert form data to natural language prompt
    let prompt = `I want to plan a trip to ${tripDetails.toLocation}`;
    
    if (tripDetails.fromLocation) {
      prompt += ` from ${tripDetails.fromLocation}`;
    }
    
    prompt += ` from ${tripDetails.startDate} to ${tripDetails.endDate}`;
    prompt += ` for ${tripDetails.travelers} ${parseInt(tripDetails.travelers) === 1 ? 'person' : 'people'}`;
    prompt += `. My budget is $${tripDetails.budget}`;
    
    if (tripDetails.pointsMiles) {
      prompt += ` and I have ${tripDetails.pointsMiles} travel points/miles to use`;
    }
    
    if (tripDetails.preferences) {
      prompt += `. Additional preferences: ${tripDetails.preferences}`;
    }

    prompt += '. Please help me plan flights, hotels, and activities!';

    setInput(prompt);
    setShowForm(false);
    setTimeout(() => handleSendMessage(prompt), 100);
  };

  const handleSendMessage = async (messageOverride = null) => {
    const messageContent = messageOverride || input;
    
    if (!messageContent.trim() || isLoading) return;

    const userMessage = {
      role: 'user',
      content: messageContent,
      timestamp: new Date()
    };

    setMessages(prev => [...prev, userMessage]);
    setInput('');
    setIsLoading(true);
    setSearchStatus('');

    try {
      // Build conversation history
      const conversationHistory = messages.map(msg => ({
        role: msg.role,
        content: msg.content
      }));

      // Add the new user message
      conversationHistory.push({
        role: 'user',
        content: messageContent
      });

      // Show searching status
      setSearchStatus('🔍 Analyzing your travel preferences...');

      // Call Claude API
      const response = await fetch('https://api.anthropic.com/v1/messages', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          model: 'claude-sonnet-4-20250514',
          max_tokens: 4000,
          messages: conversationHistory,
          system: `You are an expert AI travel agent helping users plan their trips. You have access to web search to find real-time information about flights, hotels, restaurants, and activities.

IMPORTANT INSTRUCTIONS:
1. When the user provides trip details (destination, dates, budget), search the web for:
   - Flight options and prices
   - Hotel recommendations with ratings and prices
   - Popular activities and attractions
   - Restaurant recommendations

2. As you search, describe what you're doing (e.g., "Searching for hotels in Tokyo under $150/night...")

3. After gathering information, provide a response that includes a JSON structure at the END of your message wrapped in <ITINERARY_JSON> tags. The JSON should follow this exact structure:

<ITINERARY_JSON>
{
  "destination": "City, Country",
  "startDate": "YYYY-MM-DD",
  "endDate": "YYYY-MM-DD",
  "totalBudget": 2000,
  "flights": [
    {
      "departure": "Origin City",
      "arrival": "Destination City",
      "airline": "Airline Name",
      "price": 450,
      "bookingLink": "https://www.google.com/travel/flights?q=flights+from+origin+to+destination+on+date"
    }
  ],
  "hotels": [
    {
      "name": "Hotel Name",
      "rating": 4.5,
      "price": 120,
      "address": "Hotel Address",
      "bookingLink": "https://www.booking.com/searchresults.html?ss=hotel+name+city&checkin=YYYY-MM-DD&checkout=YYYY-MM-DD"
    }
  ],
  "activities": [
    {
      "day": 1,
      "date": "YYYY-MM-DD",
      "items": [
        {
          "time": "9:00 AM",
          "activity": "Activity Name",
          "location": "Location",
          "estimatedCost": 0
        }
      ]
    }
  ],
  "restaurants": [
    {
      "name": "Restaurant Name",
      "cuisine": "Cuisine Type",
      "priceRange": "$$",
      "rating": 4.5,
      "address": "Address"
    }
  ],
  "budgetBreakdown": {
    "flights": 900,
    "hotels": 720,
    "activities": 200,
    "food": 150,
    "misc": 30,
    "total": 2000
  }
}
</ITINERARY_JSON>

4. CUSTOMIZATION MODE: If the user asks to modify an existing itinerary (add activity, change hotel, adjust budget, add restaurant, etc.):
   - Acknowledge their request conversationally
   - Make the requested changes to the itinerary
   - Return the UPDATED complete itinerary JSON with all previous items PLUS the new changes
   - Explain what you changed

5. For booking links:
   - Flights: Use Google Flights format: https://www.google.com/travel/flights?q=flights+from+{origin}+to+{destination}+on+{date}
   - Hotels: Use Booking.com format: https://www.booking.com/searchresults.html?ss={hotel+name+city}&checkin={YYYY-MM-DD}&checkout={YYYY-MM-DD}&group_adults={num_adults}
   - Replace spaces with + in URLs

6. If user mentions points/miles, incorporate that into budget calculations and mention it.

7. Keep the conversational tone warm and helpful, like a real travel agent.

8. Always return the complete updated itinerary JSON after any modification request.`
        })
      });

      const data = await response.json();
      const assistantMessage = data.content[0].text;

      // Extract itinerary JSON if present
      const jsonMatch = assistantMessage.match(/<ITINERARY_JSON>([\s\S]*?)<\/ITINERARY_JSON>/);
      if (jsonMatch) {
        try {
          const itineraryData = JSON.parse(jsonMatch[1].trim());
          const wasCustomizing = itinerary !== null; // Check if we already had an itinerary
          setItinerary(itineraryData);
          
          if (wasCustomizing) {
            // If itinerary already existed, we're in customization mode
            setIsCustomizing(true);
          } else {
            // First time creating itinerary, switch to itinerary tab
            setActiveTab('itinerary');
          }
        } catch (e) {
          console.error('Failed to parse itinerary JSON:', e);
        }
      }

      // Remove JSON tags from display message
      const displayMessage = assistantMessage.replace(/<ITINERARY_JSON>[\s\S]*?<\/ITINERARY_JSON>/g, '').trim();

      setMessages(prev => [...prev, {
        role: 'assistant',
        content: displayMessage,
        timestamp: new Date()
      }]);

      setSearchStatus('');
    } catch (error) {
      console.error('Error calling Claude API:', error);
      setMessages(prev => [...prev, {
        role: 'assistant',
        content: "I apologize, but I encountered an error while planning your trip. Please try again.",
        timestamp: new Date()
      }]);
      setSearchStatus('');
    } finally {
      setIsLoading(false);
    }
  };

  const handleKeyPress = (e) => {
    if (e.key === 'Enter' && !e.shiftKey) {
      e.preventDefault();
      handleSendMessage();
    }
  };

  const QuickPrompt = ({ icon: Icon, text, prompt }) => (
    <button
      onClick={() => setInput(prompt)}
      className="flex items-center gap-2 px-4 py-2 bg-slate-800/60 hover:bg-slate-700/60 backdrop-blur-sm rounded-full text-sm text-cyan-300 transition-all border border-cyan-500/20 shadow-md hover:shadow-cyan-500/20 font-medium"
    >
      <Icon size={14} />
      <span>{text}</span>
    </button>
  );

  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-950 via-slate-900 to-blue-950 p-4" style={{ fontFamily: '"EB Garamond", Georgia, serif' }}>
      <div className="max-w-7xl mx-auto">
        {/* Header */}
        <div className="bg-slate-900/60 backdrop-blur-2xl rounded-t-3xl shadow-2xl p-6 border-b border-blue-500/20">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-4">
              <div className="bg-gradient-to-br from-blue-500 to-cyan-500 p-3 rounded-2xl shadow-lg shadow-blue-500/20">
                <Plane className="text-white" size={26} />
              </div>
              <div>
                <h1 className="text-3xl font-bold text-white tracking-wide">Event Horizon</h1>
                <p className="text-sm text-blue-300 font-normal mt-0.5">Your intelligent journey architect</p>
              </div>
            </div>
            {itinerary && (
              <div className="flex gap-2">
                <button
                  onClick={() => {
                    setItinerary(null);
                    setIsCustomizing(false);
                    setActiveTab('chat');
                    setShowForm(true);
                  }}
                  className="flex items-center gap-2 px-4 py-2 bg-slate-700 hover:bg-slate-600 text-white rounded-xl transition-all shadow-sm font-medium text-sm"
                >
                  <Plane size={16} />
                  <span>New Journey</span>
                </button>
                <button
                  onClick={generateItineraryPDF}
                  className="flex items-center gap-2 px-4 py-2 bg-gradient-to-r from-blue-600 to-cyan-600 hover:from-blue-500 hover:to-cyan-500 text-white rounded-xl transition-all shadow-lg shadow-blue-500/20 hover:shadow-blue-500/40 font-medium text-sm"
                >
                  <Download size={16} />
                  <span>Download</span>
                </button>
                <button
                  onClick={shareItinerary}
                  className="flex items-center gap-2 px-4 py-2 bg-gradient-to-r from-blue-600 to-cyan-600 hover:from-blue-500 hover:to-cyan-500 text-white rounded-xl transition-all shadow-lg shadow-blue-500/20 hover:shadow-blue-500/40 font-medium text-sm"
                >
                  <Share2 size={16} />
                  <span>Share</span>
                </button>
              </div>
            )}
          </div>
        </div>

        {/* Main Content with Tabs */}
        <div className="bg-slate-900/60 backdrop-blur-2xl rounded-b-3xl shadow-2xl border border-blue-500/10" style={{ height: '70vh' }}>
          
          {/* Tab Navigation - Only shows when itinerary exists */}
          {itinerary && (
            <div className="flex border-b border-blue-500/20 bg-slate-800/30">
              <button
                onClick={() => setActiveTab('chat')}
                className={`flex-1 px-6 py-4 font-bold tracking-wide transition-all ${
                  activeTab === 'chat'
                    ? 'text-cyan-400 border-b-2 border-cyan-400 bg-slate-800/50'
                    : 'text-slate-400 hover:text-slate-300'
                }`}
              >
                💬 Chat & Customize
              </button>
              <button
                onClick={() => {
                  setActiveTab('itinerary');
                }}
                className={`relative flex-1 px-6 py-4 font-bold tracking-wide transition-all ${
                  activeTab === 'itinerary'
                    ? 'text-cyan-400 border-b-2 border-cyan-400 bg-slate-800/50'
                    : 'text-slate-400 hover:text-slate-300'
                }`}
              >
                🗺️ Your Itinerary
                {isCustomizing && activeTab === 'chat' && (
                  <span className="absolute top-3 right-3 w-2 h-2 bg-cyan-400 rounded-full animate-pulse"></span>
                )}
              </button>
            </div>
          )}

          {/* Chat Tab Content */}
          <div className={`flex flex-col h-full ${activeTab === 'chat' || !itinerary ? 'block' : 'hidden'}`}>
            
            {/* Structured Input Form */}
            {showForm && (
              <div className="p-6 bg-gradient-to-r from-slate-800/50 to-blue-900/30 backdrop-blur-sm border-b border-blue-500/20">
                <div className="flex items-center justify-between mb-4">
                  <h3 className="font-bold text-xl text-white tracking-wide">Trip Essentials</h3>
                  <button
                    onClick={() => setShowForm(false)}
                    className="text-xs text-blue-300 hover:text-blue-200 font-medium"
                  >
                    Hide Form
                  </button>
                </div>
                
                <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
                  {/* From Location */}
                  <div>
                    <label className="block text-xs font-medium text-blue-200 mb-1.5 tracking-wide">
                      From (Optional)
                    </label>
                    <input
                      type="text"
                      value={tripDetails.fromLocation}
                      onChange={(e) => setTripDetails({...tripDetails, fromLocation: e.target.value})}
                      placeholder="e.g., New York"
                      className="w-full px-4 py-2.5 text-sm border border-blue-500/20 rounded-xl focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent bg-slate-800/50 backdrop-blur-sm transition-all text-white placeholder-slate-500"
                    />
                  </div>

                  {/* To Location */}
                  <div>
                    <label className="block text-xs font-medium text-blue-200 mb-1.5 tracking-wide">
                      Destination <span className="text-cyan-400">*</span>
                    </label>
                    <input
                      type="text"
                      value={tripDetails.toLocation}
                      onChange={(e) => setTripDetails({...tripDetails, toLocation: e.target.value})}
                      placeholder="e.g., Tokyo"
                      className="w-full px-4 py-2.5 text-sm border border-blue-500/20 rounded-xl focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent bg-slate-800/50 backdrop-blur-sm transition-all text-white placeholder-slate-500"
                      required
                    />
                  </div>

                  {/* Start Date */}
                  <div>
                    <label className="block text-xs font-medium text-blue-200 mb-1.5 tracking-wide">
                      Start Date <span className="text-cyan-400">*</span>
                    </label>
                    <input
                      type="date"
                      value={tripDetails.startDate}
                      onChange={(e) => setTripDetails({...tripDetails, startDate: e.target.value})}
                      className="w-full px-4 py-2.5 text-sm border border-blue-500/20 rounded-xl focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent bg-slate-800/50 backdrop-blur-sm transition-all text-white"
                      required
                    />
                  </div>

                  {/* End Date */}
                  <div>
                    <label className="block text-xs font-medium text-blue-200 mb-1.5 tracking-wide">
                      End Date <span className="text-cyan-400">*</span>
                    </label>
                    <input
                      type="date"
                      value={tripDetails.endDate}
                      onChange={(e) => setTripDetails({...tripDetails, endDate: e.target.value})}
                      className="w-full px-4 py-2.5 text-sm border border-blue-500/20 rounded-xl focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent bg-slate-800/50 backdrop-blur-sm transition-all text-white"
                      required
                    />
                  </div>

                  {/* Budget */}
                  <div>
                    <label className="block text-xs font-medium text-blue-200 mb-1.5 tracking-wide">
                      Budget (USD) <span className="text-cyan-400">*</span>
                    </label>
                    <input
                      type="number"
                      value={tripDetails.budget}
                      onChange={(e) => setTripDetails({...tripDetails, budget: e.target.value})}
                      placeholder="e.g., 3000"
                      className="w-full px-4 py-2.5 text-sm border border-blue-500/20 rounded-xl focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent bg-slate-800/50 backdrop-blur-sm transition-all text-white placeholder-slate-500"
                      required
                    />
                  </div>

                  {/* Number of Travelers */}
                  <div>
                    <label className="block text-xs font-medium text-blue-200 mb-1.5 tracking-wide">
                      Travelers
                    </label>
                    <select
                      value={tripDetails.travelers}
                      onChange={(e) => setTripDetails({...tripDetails, travelers: e.target.value})}
                      className="w-full px-4 py-2.5 text-sm border border-blue-500/20 rounded-xl focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent bg-slate-800/50 backdrop-blur-sm transition-all text-white"
                    >
                      <option value="1">1 person</option>
                      <option value="2">2 people</option>
                      <option value="3">3 people</option>
                      <option value="4">4 people</option>
                      <option value="5">5+ people</option>
                    </select>
                  </div>

                  {/* Points/Miles */}
                  <div>
                    <label className="block text-xs font-medium text-blue-200 mb-1.5 tracking-wide">
                      Travel Points/Miles (Optional)
                    </label>
                    <input
                      type="text"
                      value={tripDetails.pointsMiles}
                      onChange={(e) => setTripDetails({...tripDetails, pointsMiles: e.target.value})}
                      placeholder="e.g., 50000 miles"
                      className="w-full px-4 py-2.5 text-sm border border-blue-500/20 rounded-xl focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent bg-slate-800/50 backdrop-blur-sm transition-all text-white placeholder-slate-500"
                    />
                  </div>

                  {/* Preferences */}
                  <div>
                    <label className="block text-xs font-medium text-blue-200 mb-1.5 tracking-wide">
                      Special Preferences (Optional)
                    </label>
                    <input
                      type="text"
                      value={tripDetails.preferences}
                      onChange={(e) => setTripDetails({...tripDetails, preferences: e.target.value})}
                      placeholder="e.g., vegan food, beach activities"
                      className="w-full px-4 py-2.5 text-sm border border-blue-500/20 rounded-xl focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent bg-slate-800/50 backdrop-blur-sm transition-all text-white placeholder-slate-500"
                    />
                  </div>
                </div>

                <button
                  onClick={handleFormSubmit}
                  disabled={isLoading}
                  className="mt-4 w-full px-6 py-3.5 bg-gradient-to-r from-blue-600 to-cyan-600 text-white rounded-2xl hover:from-blue-500 hover:to-cyan-500 disabled:opacity-50 disabled:cursor-not-allowed transition-all font-bold shadow-lg shadow-blue-500/30 hover:shadow-blue-500/50 tracking-wide"
                >
                  🚀 Plan My Journey
                </button>
              </div>
            )}

            {!showForm && (
              <div className="p-3 bg-slate-800/30 backdrop-blur-sm border-b border-blue-500/20">
                <button
                  onClick={() => setShowForm(true)}
                  className="text-xs text-cyan-400 hover:text-cyan-300 flex items-center gap-1 font-medium"
                >
                  <span>✏️</span> Edit Trip Details
                </button>
              </div>
            )}

            {/* Messages */}
            <div className="flex-1 overflow-y-auto p-6 space-y-4">
              {messages.map((message, index) => (
                <div
                  key={index}
                  className={`flex ${message.role === 'user' ? 'justify-end' : 'justify-start'}`}
                >
                  <div
                    className={`max-w-[80%] rounded-3xl px-5 py-3 ${
                      message.role === 'user'
                        ? 'bg-gradient-to-r from-blue-600 to-cyan-600 text-white shadow-lg shadow-blue-500/20'
                        : 'bg-slate-800/70 backdrop-blur-sm text-slate-100 border border-blue-500/10'
                    }`}
                  >
                    <p className="whitespace-pre-wrap text-sm leading-relaxed">{message.content}</p>
                    <span className="text-xs opacity-60 mt-1.5 block font-normal">
                      {message.timestamp.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}
                    </span>
                  </div>
                </div>
              ))}
              
              {searchStatus && (
                <div className="flex justify-start">
                  <div className="bg-blue-900/40 backdrop-blur-sm border border-blue-500/30 rounded-3xl px-5 py-3 flex items-center gap-2.5 text-cyan-300 shadow-lg shadow-blue-500/20">
                    <Loader2 className="animate-spin" size={16} />
                    <span className="text-sm font-medium">{searchStatus}</span>
                  </div>
                </div>
              )}
              
              {isLoading && !searchStatus && (
                <div className="flex justify-start">
                  <div className="bg-slate-800/70 backdrop-blur-sm rounded-3xl px-5 py-3 flex items-center gap-2.5 shadow-lg border border-blue-500/10">
                    <Loader2 className="animate-spin text-cyan-400" size={16} />
                    <span className="text-sm text-slate-300 font-medium">Planning your journey...</span>
                  </div>
                </div>
              )}
              
              <div ref={messagesEndRef} />
            </div>

            {/* Quick Prompts */}
            {messages.length === 1 && !showForm && !itinerary && (
              <div className="px-6 pb-4">
                <p className="text-sm text-slate-400 mb-2 italic">Or try a quick example:</p>
                <div className="flex flex-wrap gap-2">
                  <QuickPrompt
                    icon={MapPin}
                    text="Tokyo Adventure"
                    prompt="I want to explore Tokyo's food scene and visit temples. Any suggestions?"
                  />
                  <QuickPrompt
                    icon={Calendar}
                    text="Add Activities"
                    prompt="What are some must-see attractions and activities I should add?"
                  />
                </div>
              </div>
            )}

            {/* Customization Prompts - Shows after itinerary is generated */}
            {itinerary && !isLoading && (
              <div className="px-6 pb-4">
                <p className="text-sm text-cyan-300 mb-2 font-semibold">✨ Customize Your Journey:</p>
                <div className="flex flex-wrap gap-2">
                  <QuickPrompt
                    icon={MapPin}
                    text="Add Activity"
                    prompt="Can you suggest and add a unique local experience or activity?"
                  />
                  <QuickPrompt
                    icon={Calendar}
                    text="Add Restaurant"
                    prompt="Recommend a highly-rated restaurant and add it to my itinerary."
                  />
                  <QuickPrompt
                    icon={DollarSign}
                    text="Cut Budget"
                    prompt="Can you make this itinerary more budget-friendly?"
                  />
                  <button
                    onClick={() => setInput("Change my hotel to something more luxurious")}
                    className="flex items-center gap-2 px-4 py-2 bg-slate-800/60 hover:bg-slate-700/60 backdrop-blur-sm rounded-full text-sm text-cyan-300 transition-all border border-cyan-500/20 shadow-md hover:shadow-cyan-500/20 font-medium"
                  >
                    <MapPin size={14} />
                    <span>Upgrade Hotel</span>
                  </button>
                </div>
              </div>
            )}

            {/* Input */}
            <div className="p-6 border-t border-blue-500/20">
              <div className="flex gap-3">
                <textarea
                  value={input}
                  onChange={(e) => setInput(e.target.value)}
                  onKeyPress={handleKeyPress}
                  placeholder={itinerary ? "Customize your journey (add activities, change hotels, modify budget...)" : "Describe your dream journey..."}
                  className="flex-1 px-4 py-3 border border-blue-500/20 rounded-2xl focus:outline-none focus:ring-2 focus:ring-cyan-500 focus:border-transparent resize-none bg-slate-800/50 backdrop-blur-sm transition-all text-sm text-white placeholder-slate-500"
                  rows="2"
                  disabled={isLoading}
                />
                <button
                  onClick={handleSendMessage}
                  disabled={!input.trim() || isLoading}
                  className="px-6 py-3 bg-gradient-to-r from-blue-600 to-cyan-600 text-white rounded-2xl hover:from-blue-500 hover:to-cyan-500 disabled:opacity-40 disabled:cursor-not-allowed transition-all shadow-lg shadow-blue-500/20 hover:shadow-blue-500/40"
                >
                  <Send size={18} />
                </button>
              </div>
            </div>
          </div>

          {/* Itinerary Tab Content */}
          <div className={`flex flex-col h-full overflow-y-auto ${activeTab === 'itinerary' && itinerary ? 'block' : 'hidden'}`}>
            
            {/* Customization Banner */}
            <div className="p-4 bg-gradient-to-r from-blue-900/40 to-cyan-900/40 border-b border-cyan-500/20">
              <div className="flex items-center justify-between">
                <div>
                  <p className="text-cyan-300 font-semibold text-sm">✨ Want to customize your itinerary?</p>
                  <p className="text-slate-400 text-xs mt-1">Switch to chat to add activities, change hotels, or adjust your plan</p>
                </div>
                <button
                  onClick={() => setActiveTab('chat')}
                  className="px-4 py-2 bg-cyan-500 hover:bg-cyan-400 text-white rounded-xl font-medium text-sm transition-all shadow-lg shadow-cyan-500/20"
                >
                  Go to Chat
                </button>
              </div>
            </div>

            <div className="p-6 space-y-6">
                {/* Trip Overview */}
                <div className="bg-gradient-to-r from-blue-600 to-cyan-600 text-white p-5 rounded-2xl shadow-xl shadow-blue-500/20">
                  <h3 className="font-bold text-xl tracking-wide">{itinerary.destination}</h3>
                  <p className="text-sm opacity-90 mt-1">{itinerary.startDate} to {itinerary.endDate}</p>
                  <p className="text-sm opacity-90 mt-0.5">Budget: ${itinerary.totalBudget}</p>
                </div>

                {/* Flights */}
                {itinerary.flights && itinerary.flights.length > 0 && (
                  <div>
                    <h4 className="font-bold text-white mb-3 flex items-center gap-2 tracking-wide text-lg">
                      <Plane size={18} className="text-cyan-400" />
                      Flights
                    </h4>
                    {itinerary.flights.map((flight, idx) => (
                      <div key={idx} className="bg-slate-800/60 backdrop-blur-sm p-4 rounded-2xl mb-2 border border-cyan-500/20 shadow-lg hover:shadow-cyan-500/20 transition-all">
                        <p className="font-semibold text-sm text-white">{flight.departure} → {flight.arrival}</p>
                        <p className="text-xs text-slate-400 mt-1">{flight.airline} • ${flight.price}</p>
                        <a
                          href={flight.bookingLink}
                          target="_blank"
                          rel="noopener noreferrer"
                          className="text-xs text-cyan-400 hover:text-cyan-300 flex items-center gap-1 mt-2 font-medium"
                        >
                          Book Now <ExternalLink size={11} />
                        </a>
                      </div>
                    ))}
                  </div>
                )}

                {/* Hotels */}
                {itinerary.hotels && itinerary.hotels.length > 0 && (
                  <div>
                    <h4 className="font-bold text-white mb-3 flex items-center gap-2 tracking-wide text-lg">
                      <MapPin size={18} className="text-cyan-400" />
                      Accommodations
                    </h4>
                    {itinerary.hotels.map((hotel, idx) => (
                      <div key={idx} className="bg-slate-800/60 backdrop-blur-sm p-4 rounded-2xl mb-2 border border-cyan-500/20 shadow-lg hover:shadow-cyan-500/20 transition-all">
                        <p className="font-semibold text-sm text-white">{hotel.name}</p>
                        <p className="text-xs text-slate-400 mt-1">⭐ {hotel.rating} • ${hotel.price}/night</p>
                        <p className="text-xs text-slate-500 mt-1.5">{hotel.address}</p>
                        <a
                          href={hotel.bookingLink}
                          target="_blank"
                          rel="noopener noreferrer"
                          className="text-xs text-cyan-400 hover:text-cyan-300 flex items-center gap-1 mt-2 font-medium"
                        >
                          Book Now <ExternalLink size={11} />
                        </a>
                      </div>
                    ))}
                  </div>
                )}

                {/* Daily Activities */}
                {itinerary.activities && itinerary.activities.length > 0 && (
                  <div>
                    <h4 className="font-bold text-white mb-3 flex items-center gap-2 tracking-wide text-lg">
                      <Calendar size={18} className="text-cyan-400" />
                      Daily Plan
                    </h4>
                    {itinerary.activities.map((day, idx) => (
                      <div key={idx} className="mb-3">
                        <p className="text-sm font-semibold text-cyan-300 mb-2">Day {day.day} - {day.date}</p>
                        <div className="bg-slate-800/60 backdrop-blur-sm p-4 rounded-2xl space-y-2 border border-cyan-500/20 shadow-lg">
                          {day.items.map((item, itemIdx) => (
                            <div key={itemIdx} className="text-xs">
                              <span className="font-bold text-white">{item.time}</span>
                              <span className="text-slate-300"> - {item.activity}</span>
                              {item.location && <span className="text-slate-500"> ({item.location})</span>}
                            </div>
                          ))}
                        </div>
                      </div>
                    ))}
                  </div>
                )}

                {/* Restaurants */}
                {itinerary.restaurants && itinerary.restaurants.length > 0 && (
                  <div>
                    <h4 className="font-bold text-white mb-3 tracking-wide text-lg">🍽️ Restaurants</h4>
                    {itinerary.restaurants.map((restaurant, idx) => (
                      <div key={idx} className="bg-slate-800/60 backdrop-blur-sm p-4 rounded-2xl mb-2 border border-cyan-500/20 shadow-lg hover:shadow-cyan-500/20 transition-all">
                        <p className="font-semibold text-sm text-white">{restaurant.name}</p>
                        <p className="text-xs text-slate-400 mt-1">{restaurant.cuisine} • {restaurant.priceRange} • ⭐ {restaurant.rating}</p>
                        <p className="text-xs text-slate-500 mt-1.5">{restaurant.address}</p>
                      </div>
                    ))}
                  </div>
                )}

                {/* Budget Breakdown */}
                {itinerary && itinerary.budgetBreakdown && (
                  <div className="bg-slate-800/60 backdrop-blur-sm p-5 rounded-2xl border border-cyan-500/20 shadow-xl">
                    <h4 className="font-bold text-white mb-3 tracking-wide text-lg">💰 Budget Breakdown</h4>
                    <div className="space-y-2 text-sm">
                      <div className="flex justify-between">
                        <span className="text-slate-400">Flights:</span>
                        <span className="font-semibold text-white">${itinerary.budgetBreakdown.flights}</span>
                      </div>
                      <div className="flex justify-between">
                        <span className="text-slate-400">Hotels:</span>
                        <span className="font-semibold text-white">${itinerary.budgetBreakdown.hotels}</span>
                      </div>
                      <div className="flex justify-between">
                        <span className="text-slate-400">Activities:</span>
                        <span className="font-semibold text-white">${itinerary.budgetBreakdown.activities}</span>
                      </div>
                      <div className="flex justify-between">
                        <span className="text-slate-400">Food:</span>
                        <span className="font-semibold text-white">${itinerary.budgetBreakdown.food}</span>
                      </div>
                      <div className="flex justify-between">
                        <span className="text-slate-400">Misc:</span>
                        <span className="font-semibold text-white">${itinerary.budgetBreakdown.misc}</span>
                      </div>
                      <div className="flex justify-between pt-3 border-t border-cyan-500/30">
                        <span className="font-bold text-white">Total:</span>
                        <span className="font-bold text-cyan-400">${itinerary.budgetBreakdown.total}</span>
                      </div>
                    </div>
                  </div>
                )}
            </div>
          </div>
        </div>

        {/* Footer */}
        <div className="text-center mt-6 text-xs text-slate-600 font-medium italic">
          <p>Powered by Claude AI • Event Horizon © 2025</p>
        </div>
      </div>
    </div>
  );
};

export default TravelPlannerAgent;
